/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutilsRouteImport } from './routes/outils'
import { Route as NavigateurRouteImport } from './routes/navigateur'
import { Route as LecteurRouteImport } from './routes/lecteur'
import { Route as EnRouteImport } from './routes/en'
import { Route as CodecRouteImport } from './routes/codec'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnToolsRouteImport } from './routes/en.tools'

const OutilsRoute = OutilsRouteImport.update({
  id: '/outils',
  path: '/outils',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateurRoute = NavigateurRouteImport.update({
  id: '/navigateur',
  path: '/navigateur',
  getParentRoute: () => rootRouteImport,
} as any)
const LecteurRoute = LecteurRouteImport.update({
  id: '/lecteur',
  path: '/lecteur',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const CodecRoute = CodecRouteImport.update({
  id: '/codec',
  path: '/codec',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnToolsRoute = EnToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codec': typeof CodecRoute
  '/en': typeof EnRouteWithChildren
  '/lecteur': typeof LecteurRoute
  '/navigateur': typeof NavigateurRoute
  '/outils': typeof OutilsRoute
  '/en/tools': typeof EnToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codec': typeof CodecRoute
  '/en': typeof EnRouteWithChildren
  '/lecteur': typeof LecteurRoute
  '/navigateur': typeof NavigateurRoute
  '/outils': typeof OutilsRoute
  '/en/tools': typeof EnToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codec': typeof CodecRoute
  '/en': typeof EnRouteWithChildren
  '/lecteur': typeof LecteurRoute
  '/navigateur': typeof NavigateurRoute
  '/outils': typeof OutilsRoute
  '/en/tools': typeof EnToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codec'
    | '/en'
    | '/lecteur'
    | '/navigateur'
    | '/outils'
    | '/en/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/codec'
    | '/en'
    | '/lecteur'
    | '/navigateur'
    | '/outils'
    | '/en/tools'
  id:
    | '__root__'
    | '/'
    | '/codec'
    | '/en'
    | '/lecteur'
    | '/navigateur'
    | '/outils'
    | '/en/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodecRoute: typeof CodecRoute
  EnRoute: typeof EnRouteWithChildren
  LecteurRoute: typeof LecteurRoute
  NavigateurRoute: typeof NavigateurRoute
  OutilsRoute: typeof OutilsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outils': {
      id: '/outils'
      path: '/outils'
      fullPath: '/outils'
      preLoaderRoute: typeof OutilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigateur': {
      id: '/navigateur'
      path: '/navigateur'
      fullPath: '/navigateur'
      preLoaderRoute: typeof NavigateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecteur': {
      id: '/lecteur'
      path: '/lecteur'
      fullPath: '/lecteur'
      preLoaderRoute: typeof LecteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codec': {
      id: '/codec'
      path: '/codec'
      fullPath: '/codec'
      preLoaderRoute: typeof CodecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/tools': {
      id: '/en/tools'
      path: '/tools'
      fullPath: '/en/tools'
      preLoaderRoute: typeof EnToolsRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface EnRouteChildren {
  EnToolsRoute: typeof EnToolsRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnToolsRoute: EnToolsRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodecRoute: CodecRoute,
  EnRoute: EnRouteWithChildren,
  LecteurRoute: LecteurRoute,
  NavigateurRoute: NavigateurRoute,
  OutilsRoute: OutilsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
